# 머신러닝
## 2일차
- 열심히 하자
- 오늘도 여전히

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = [[5.1, 3.5, 1.4], [4.9, 3.0, 1.4],
     [4.7, 3.2, 1.3], [4.6, 3.1, 1.5],
     [5.0, 3.6, 1.4]]

X

[[5.1, 3.5, 1.4],
 [4.9, 3.0, 1.4],
 [4.7, 3.2, 1.3],
 [4.6, 3.1, 1.5],
 [5.0, 3.6, 1.4]]

In [3]:
y = [0.2, 0.4, 0.3, 0.2, 0.3]
y

[0.2, 0.4, 0.3, 0.2, 0.3]

In [5]:
X = np.array(X)
X

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [6]:
y = np.array(y)
y

array([0.2, 0.4, 0.3, 0.2, 0.3])

In [ ]:
w1 = 1.0
w2 = 1.0
w3 = 1.0
b = 1.0

- 가중치를 초기화

In [7]:
W = np.array([1.0, 1.0, 1.0]) ############
b = 1.0

- 예측값을 출력

In [8]:
result_y = X@W + b # 행렬곱
result_y

array([11. , 10.3, 10.2, 10.2, 11. ])

In [9]:
result_y = (X*W).sum(axis=1) + b
result_y

array([11. , 10.3, 10.2, 10.2, 11. ])

In [16]:
y

array([0.2, 0.4, 0.3, 0.2, 0.3])

- 오차값 (비용함수 적용 -> MSE)

In [10]:
오차값 = ((y - result_y)**2).mean() # MSE
오차값

105.42999999999999

- 가중치 변경 (W, b)

In [11]:
W = W - 0.5
b = b - 0.5
W, b

(array([0.5, 0.5, 0.5]), 0.5)

In [12]:
result_y = (X*W).sum(axis=1) + b
result_y

array([5.5 , 5.15, 5.1 , 5.1 , 5.5 ])

In [13]:
오차값 = ((y - result_y)**2).mean() # MSE
오차값

24.948500000000003